publishDir = "./public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseURL = "https://Bit-GraphML.github.io"
relativeURLs = true
uglyURLs = true
theme = "hugo-academic-group"
title = "北京理工大学图数据科学实验室"
math = true
copyright = "&copy; 李洵楷、杨世宇, 2022 "

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of research group"
  author = "李荣华"
  email = "lironghuabit@126.com"
  address = "北京市海淀区中关村南大街5号中心教学楼1233"

  slogan = "图数据科学实验室"
  slogan_text = "图算法研究"

  [[params.slogan_columns]]
    title = "研究方向"
    text =  "图数据管理与挖掘、图计算系统、图神经网络、图表示学习、知识图谱、图论算法的设计与分析、谱图理论、图数据隐私保护、图联邦学习等。"
    link = "/about"
    link_text = "Meet the team"
    weight = 1
  
  [[params.slogan_columns]]
    title = "招聘信息"  
    text = "长期招收博士后科研人员。主要工作包括：(a)力争做出高水平科研成果; (b)协助指导课题组学生。\n 每年招收博士生1人、硕士生4人（有较强的数学功底或者有ACM程序设计竞赛经历的同学将被优先考虑）。\n长期招聘本科实习生，进入课题组的本科生将由我和我的博士生共同指导。\n  欢迎有意加入本课题组的人员发邮件咨询： lironghuabit@126.com"
    link = "/mission"
    link_text = "Read more"
    weight = 2

  [[params.slogan_columns]]
    title = "正在指导的学生"
    text = "博士后：秦宏超 博士生：张琦(2018级)代强强(2019级)，廖美昊(2020级)，李泽宁(2021级)，李洵楷(2022级) 硕士生：任泽槟(2019级)，高森(2019级)，徐兰天(2019级)，潘敏佳(2019级)，陈久健(2020级)，陈子健(2020级)，程苗苗(2020级)，龙水彬(2020级)，蒋佳祺(2021级)，叶小伟(2021级)，曾越(2021级)，马泽航(2021级)，胡仲则(2021级)"
    link = "/approach"
    link_text = "师生合影"
    weight = 3

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "联系方式"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]]
      name = "Research"
      url = "/research"
      weight = 2

  [[menu.main]]
      name = "Publications"
      url = "/#publications"
      weight = 3

    [[menu.main]]
      name = "Projects"
      url = "/#projects"
      weight = 4

  [[menu.main]]
      name = "Members"
      url = "/#members"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "/#posts"
      weight = 6


  [[menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 7
